<?php $theme = Mage::helper('wsu_themecontrol'); ?>
<meta http-equiv="Content-Type" content="<?=$this->getContentType();?>" />
<title><?=$this->getTitle();?></title>
<?php if ($theme->getCfgLayout('responsive/responsive')): ?>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
<?php endif; ?>
<meta name="description" content="<?=htmlspecialchars($this->getDescription());?>" />
<meta name="keywords" content="<?=htmlspecialchars($this->getKeywords());?>" />
<meta name="robots" content="<?=htmlspecialchars($this->getRobots());?>" />
<link rel="icon" href="<?=$this->getFaviconFile();?>" type="image/x-icon" />
<link rel="shortcut icon" href="<?=$this->getFaviconFile();?>" type="image/x-icon" />

<?=$this->getCssJsHtml();?>
<?=$this->getChildHtml();?>
<?=$this->helper('core/js')->getTranslatorScript();?>
<?=$this->getIncludes();?>

<noscript><style>#spine .spine-sitenav ul ul li { display: block !important; }</style></noscript>

<!-- DOCS -->
<link type="text/plain" rel="author" href="http://repo.wsu.edu/spine/1/authors.txt" />
<link type="text/html" rel="docs" href="http://brand.wsu.edu" />

<?php if ($theme->getCfgDesign('font/primary_font_family_group') == 'google'): ?>
	<?php //Include Google Fonts
		$amp = '&amp;';
		$charSubset = '';
		if ($subsets = $theme->getCfgDesign('font/primary_char_subset')) {
			$charSubset = "{$amp}subset={$subsets}";
		}
	
		$fontWeight = '';
		if ($weight = $theme->getCfgDesign('font/primary_font_weight')) {
			$fontWeight = ':' . $weight;
		}
	?>
	<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $theme->getCfgDesign('font/primary_font_family')); 
		echo $fontWeight; echo $charSubset; ?>' rel='stylesheet' type='text/css' />
<?php endif;?>

