<?php
$layout = $this->helper('wsu_themecontrol/layout');

$layout->set_layoutTarget('catalog_product_view/productview');
?>
<div class="product-options <?=$layout->getLayoutBlockClass("product-options")?>" id="product-options-wrapper">
    <?php echo $this->getChildHtml('', true, true);?>
    <?php if ($this->hasRequiredOptions()):?>
        <p class="required"><?php echo $this->__('* Required Fields') ?></p>
    <?php endif;?>
	<script type="text/javascript">decorateGeneric($$('#product-options-wrapper dl'), ['last']);</script>
</div>

