<?php
/**
 * Template for Mage_Page_Block_Html
 */
$lang=$this->getLang();
$store = Mage::app()->getStore();
$name = $store->getFrontendName();
$random = array('n1','n2','n3','n4');
$storeId = $store->getStoreId();
$storeCode = $store->getCode();
$theme = $this->helper('wsu_themecontrol');
$binderClassStr = $theme->getBinderClassStr($storeCode);
$binderStyleStr =  $theme->getBinderStyleStr($storeCode);
$bodyClasses = $this->getBodyClass() .' '. $theme->getThemeBodyClasses() .' '. $random[rand(0,2)];
$spine_tool_bar_color = $theme->getCfgDesign('spine/spine_tool_bar_color');
?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js no-svg lt-ie9 lt-ie8 lt-ie7" lang="<?=$lang ?>"> <![endif]-->
<!--[if IE 7]><html class="no-js no-svg lt-ie9 lt-ie8" lang="<?=$lang ?>"> <![endif]-->
<!--[if IE 8]><html class="no-js no-svg lt-ie9" lang="<?=$lang ?>"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="<?=$lang ?>"><!--<![endif]-->
<head>
	<?=$this->getChildHtml('head')?>
</head>
<body class=" <?=$bodyClasses?>">
    <!-- WRAPPING -->
    <div id="jacket">
        <div id="binder" class="<?=$binderClassStr?>" style="<?=$binderStyleStr?>">
            <!-- CONTENT -->
            <main id="page" role="main">
                <section class="row" id="siteID">
                    <div style="float:right;">
                        <div class="quick-access <?=$spine_tool_bar_color; ?>" style="font-size:12px; font-weight:bold;">
                            <?php echo $this->getChildHtml('topLinks') ?>
                        </div>
                    </div>
                </section>
                <!-- Responsive Sections -->
                <section class="row">
                    <div class="column ten-twelfths">
                        <article>
                            <h2>WSU Marketplace</h2>
                            <h1><?=$name?></h1>
                            <?php echo $this->getChildHtml('breadcrumbs') ?> 
                        </article>
                        <article>
                        	<?php echo $this->getChildHtml('after_body_start') ?>
                            <div id="main">
                                <?php echo $this->getChildHtml('topContainer'); ?>
                                <?php echo $this->getChildHtml('global_notices') ?>
                                <?php echo $this->getChildHtml('global_messages') ?>
                                <?php echo $this->getChildHtml('content') ?>
                            </div><!-- end of main -->   
                        </article>
                    </div><!--/column-->
                    <div class="column two-twelfths ">
                        <aside>
                            <section>
                            	<?php echo $this->getChildHtml('left'); ?>
                            </section>
                        </aside>
                    </div><!--/column-->
                </section>
                <footer>
					<?php echo $this->getChildHtml('footer') ?>
                    
                    <?php echo $this->getAbsoluteFooter() ?>
				</footer>
            </main><!--/#page-->
            <!-- /CONTENT -->
    
            <?php echo $this->getChildHtml('header') ?>
        </div><!--/cover-->
    </div><!--/jacket-->
    <!-- /WRAPPING -->
    <?php echo $this->getChildHtml('before_body_end') ?>
</body>
</html>
