<?php
/**
 * Template for Mage_Page_Block_Html
 */
$lang=$this->getLang();
$store = Mage::app()->getStore();
$name = $store->getFrontendName();
$randomClass = 'five'.rand(0,5).' ten'.rand(0,10);
$storeId = $store->getStoreId();
$storeCode = $store->getCode();
$theme = $this->helper('wsu_themecontrol');
$binderClassStr = $theme->getBinderClassStr($storeCode);
$binderStyleStr =  $theme->getBinderStyleStr($storeCode);
$bodyClasses = $storeCode.$storeId.' '.$this->getBodyClass() .' '. $theme->getThemeBodyClasses() .' '. $randomClass;
$spine_tool_bar_color = $theme->getCfgDesign('spine/spine_tool_bar_color');
?>
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js no-svg lt-ie9 lt-ie8 lt-ie7" lang="<?=$lang ?>"> <![endif]-->
<!--[if IE 7]><html class="no-js no-svg lt-ie9 lt-ie8" lang="<?=$lang ?>"> <![endif]-->
<!--[if IE 8]><html class="no-js no-svg lt-ie9" lang="<?=$lang ?>"> <![endif]-->
<!--[if gt IE 8]><!--><html class="no-js" lang="<?=$lang ?>"><!--<![endif]-->
<head>
	<?=$this->getChildHtml('head')?>
</head>
<?php $bodyClasses = $this->getBodyClass() .' '. $this->helper('wsu_themecontrol')->getThemeBodyClasses() .' '. $random[rand(0,2)]; ?>
<body class=" <?=$bodyClasses?>">
	<?php echo $this->getChildHtml('after_body_start') ?>
    <div id = "wrapper">
<?php echo $this->getChildHtml('header') ?>
			<?php echo $this->getChildHtml('right') ?>
            <?php echo $this->getChildHtml('left') ?>
        </div><!--end nav-->
            <div id="main">
				<?php echo $this->getChildHtml('topContainer'); ?>
				<?php echo $this->getChildHtml('topBar') ?>
                <?php echo $this->getChildHtml('global_notices') ?>
                <?php echo $this->getChildHtml('global_messages') ?>
                <?php echo $this->getChildHtml('content') ?>
            </div><!-- end of main -->
            <div id="localfooter">
            	<?php echo $this->getChildHtml('footer') ?><a href="http://publishing.wsu.edu/">University Publishing</a>, Washington State University, PO Box 645910, Pullman, WA, 99164-5910 USA 509-335-3518 <a href="mailto:publishing@wsu.edu">Contact Us</a>
            </div>
            
        </div><!-- end of content -->
    </div><!-- end of wrapper -->
	
    <?php echo $this->getChildHtml('before_body_end') ?>
	<?php echo $this->getAbsoluteFooter() ?>
    <div id="wsufooter"><a href="http://publishing.wsu.edu/copyright/Wsu.html">&copy; 2013</a> <a href="http://www.wsu.edu">Washington State University</a> | <a href="http://access.wsu.edu/">Accessibility</a> | <a href="http://policies.wsu.edu/">Policies</a> | <a href="http://publishing.wsu.edu/copyright/Wsu.html">Copyright</a></div>
</body>
</html>
