<?php
/**
 * Currency switcher
 *
 * @see Mage_Directory_Block_Currency
 */
?>
<?php if($this->getCurrencyCount()>1): ?>

	<?php
		$currCurrencyName;
		$html = array();
		$html[] = '<ul class="dropdown-menu left-hand">';
		foreach ($this->getCurrencies() as $_code => $_name) {
			if($_code == $this->getCurrentCurrencyCode()) {
				$currCurrencyName = $_code;
				$html[] = '<li class="current">'. $_code .' - '. $_name .'</li>';
			} else {
				$html[] = '<li><a href="'. $this->getSwitchCurrencyUrl($_code) .'">'. $_code .' - '. $_name .'</a></li>';
			}
		}
		$html[] = '</ul>';
    ?>
    <div class="dropdown currency-switcher item item-right">
        <div class="dropdown-toggle cover">
            <div>
                <div class="label hide-below-768"><?php echo $this->__('Currency'); ?>:</div>
                <div class="value"><?php echo $currCurrencyName; ?></div>
                <span class="caret">&nbsp;</span>
            </div>
        </div>
        <?php echo implode('', $html); ?>
    </div>
<?php endif; ?>
