<?php
/**
 * - Removed links to review page and review form
 */
?>
<?php if ($this->getReviewsCount()): ?>
    <div class="ratings">
        <?php if ($this->getRatingSummary()):?>
            <div class="rating-box">
                <div class="rating" style="width:<?php echo $this->getRatingSummary() ?>%"></div>
            </div>
        <?php endif;?>
        <span class="amount"><?php echo $this->__('%d Review(s)', $this->getReviewsCount()) ?></span>
    </div>
<?php elseif ($this->getDisplayIfEmpty()): ?>
    <p class="no-rating"><?php echo $this->__('Be the first to review this product') ?></p>
<?php endif; ?>
