<?php if($this->getCollection()->getSize()): ?>
<div class="cat_list_header_bottom">
<?php //echo $this->getLayout()->createBlock('page/html_pager', 'bottom.pager')->setTemplate('page/html/bottom-pager.phtml')->toHtml(); 

$blocks = Mage::app()->getLayout()->getAllBlocks();
//$blockNames = array_keys($blocks);
//var_dump($blocks['product_list_toolbar_pager']);
?>

<?php echo $this->getPagerHtml() ?>
	<?php echo $this->getProductListToolbarPagerBlock()->setTemplate('page/html/bottom-pager.phtml')->toHtml();?>
	product_list_toolbar_pager
</div>
<?php endif ?>
