<?php

	$products_limit	= (int)$this->getData('products_limit');
	$imgh	= (int)$this->getData('imgh');
	$imgw	= (int)$this->getData('imgw');
	
	$_store=Mage::app()->getStore();
	$storeId=$_store->getStoreId();
	$store=Mage::getModel('core/store')->load($storeId);
	
	$collection = Mage::getResourceModel('reports/product_collection');
	$collection->addStoreFilter($storeId);
	$total_products_in_store = $collection->getSize();	
	if($total_products_in_store>0){
		$_rootcatID = $store->getRootCategoryId();				
		$cat = Mage::getModel('catalog/category')->load($_rootcatID);
		$subcats = $cat->getChildren();
		$cats = array();
		foreach(explode(',',$subcats) as $subCatid) {
		  $_category = Mage::getModel('catalog/category')->load($subCatid);
		  if($_category->getIsActive()) {
			$sub_cat = Mage::getModel('catalog/category')->load($_category->getId());
			$cats[]=$_category->getId();
			
			$sub_subcats = $sub_cat->getChildren();
			foreach(explode(',',$sub_subcats) as $sub_subCatid) {
				  $_sub_category = Mage::getModel('catalog/category')->load($sub_subCatid);
				  if($_sub_category->getIsActive()) {
					 $cats[]=$_sub_category->getId();
				  }
			 }
		  }
		}
		$randCollection = null;
		$randCollection = Mage::getResourceModel('catalog/product_collection')
			->joinField('category_id','catalog/category_product','category_id','product_id=entity_id',null,'left')
			->addAttributeToFilter('category_id', array('in' => $cats))
			->addAttributeToFilter('small_image', array('neq' => ''))
			->addAttributeToFilter('small_image', array('neq' => 'no_selection'))
			->addAttributeToSelect('*'); 					
		$randCollection->getSelect()->order(new Zend_Db_Expr('RAND()'));
		$randCollection->setPage(1,$products_limit);
		$j=0;
		if(!empty($randCollection) && count($randCollection)>0){
			$content="";
			foreach($randCollection as $product){
				$_proId =  $product->getId();
				$_product= $product; 
				$content .= "<div class='column four-twelfths product_feature'><a href='" . $_product->getProductUrl() . "'  style='display:inline-block;float:left;'><img src='". $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgw,$imgh) ."' alt='' width='".$imgw."' border='0' /></a> <p style='padding:5px;margin-left:".$imgw."px'><a href='" .$_product->getProductUrl(). "'>" .$this->htmlEscape($_product->getName()). "</a></p></div>";
			}
			echo $content;
		}
		
		
	}
?>