<?php
$productId = $this->getProduct_id();



$urlpath = $this->getUrlpath();
if(!$productId && $urlpath!=""){

    $vPath = 'electronics/cameras/olympus-stylus-750-7-1mp-digital-camera.html';
    $oRewrite = Mage::getModel('core/url_rewrite')->loadByRequestPath($vPath);
	$productId = $oRewrite->getProductId();
					
}


$_product = Mage::getModel('catalog/product')->load($productId);
$loadfull = $this->getLoad_full();

if(!$loadfull):
?>
    <a href="<?php echo $_product->getProductUrl() ?>"><img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(95, 95); ?>" alt="" width="95" border="0" /></a>
    <div class="product-description">
        <p><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></p>
        <!--<p>See all <a href="{{store direct_url="electronics/computers/laptops.html"}}">Laptops</a></p>-->
    </div>

<?php else: ?>


    
    <div class="featured-product-box">
    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" target="_top"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(115, 115); ?>" width="115" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" /></a>
    <h2><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" target="_top"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
    <?php if($_product->getRatingSummary()): ?>
    <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
    <?php endif; ?>
    <div>
    <?php echo nl2br($_product->getShortDescription()); ?>
    </div>
    <div class='price-block'>
    
    <?php echo $this->getPriceHtml($_product, true) ?>
    
    </div>
    <div>
    <?php if($_product->isSaleable()): ?>
    <a href="/checkout/cart/add?product=<?php echo $_product->getId() ?>" target="_parent"><img border="0" alt="Add to Cart" src="<?php echo $this->getSkinUrl('images/btn_addtocart_small.gif')?>"></a>
    <?php else: ?>
    <p><span><?php echo $this->__('Out of stock') ?></span></p>
    <?php endif; ?>
    
    </div>
    </div>

<?php endif; ?>