<?php
/**
 * Downloadable product type
 *
 * @see Mage_Downloadable_Block_Catalog_Product_View_Type
 */
?>
<?php $_product = $this->getProduct() ?>

<?php echo $this->getChildHtml('product_type_data_extra') ?>
<?php echo $this->getChildHtml('samples') ?>
<div class="space-before-avail"></div>
<?php if($_product->isSaleable()): ?>
    <p class="availability in-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('In stock') ?></span></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo $this->__('Availability:') ?> <span><?php echo $this->__('Out of stock') ?></span></p>
<?php endif; ?>
<?php echo $this->getPriceHtml($_product) ?>
