/**
 * WARNING: do not edit this file. It was generated automatically, your changes will be overwritten and lost.
 * 2016-05-13 16:07:24 */

(function($){
    alert("hello from the global");
}(jQuery))