<div id="localfooter">
	<section class="row sidebar">

        <div class="column one">
    
            <article class="post-138 page type-page status-publish hentry" id="post-138">
				<?php echo $this->getChildHtml() ?> 
                <address><?php echo $this->getCopyright() ?></address>
                <script type="text/javascript">
                   // To display the "Print" link pass in true.  To hide the "Print" link pass in false.
                   //addPrintLink(true);
                </script>
                <a href="http://web.wsu.edu/">University Web Communications</a>, Washington State University, PO Box 645910, Pullman, WA, 99164-5910 USA 509-335-5555 <a href="mailto:dev.hotseat@wsu.edu">Contact Us</a>
            </article>
        </div>
    </section>
</div>