<div id="localfooter">
	<?php echo $this->getChildHtml() ?> 
	<address><?php echo $this->getCopyright() ?></address>
	<script type="text/javascript">
       // To display the "Print" link pass in true.  To hide the "Print" link pass in false.
       //addPrintLink(true);
    </script>
	<a href="http://publishing.wsu.edu/">University Publishing</a>, Washington State University, PO Box 645910, Pullman, WA, 99164-5910 USA 509-335-3518 <a href="mailto:publishing@wsu.edu">Contact Us</a>
</div>