<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<link rel="shortcut icon" href="http://images.wsu.edu/favicon.ico" />
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />
<!--[if lt IE 7]>
<script type="text/javascript">
//<![CDATA[
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
//]]>
</script>
<![endif]-->

<!--<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://images.wsu.edu/javascripts/print_v2.js" type="text/javascript"></script>-->
<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>
<!--<link href="http://designer.wsu.edu/template/css2.aspx?key=0eab28zs011" type="text/css" rel="stylesheet" />-->
<link href="http://nbj.me/spine/1/styles.css" rel="stylesheet" type="text/css" />
<link href="<?=$this->getSkinUrl('css/quickoverride.css')?>" type="text/css" rel="stylesheet" />

<meta name="viewport" content="width=device-width, user-scalable=yes">
<!-- DOCS -->
<link type="text/plain" rel="author" href="http://images.wsu.edu/spine/humans.txt" />
<link type="text/html" rel="docs" href="http://identity.wsu.edu" />




