<?php
/**
 * @see Mage_CatalogInventory_Block_Stockqty_Composite
 */
?>
<?php if($this->isMsgVisible()): ?>

	<a class="availability-only feature feature-icon-hover v-centered-content" href="#" id="<?php echo $this->getPlaceholderId() ?>" title="<?php echo $this->__('Only %s left', ($this->getStockQty())) ?>">
		<span class="v-center">
			<span class="icon i-lowstock-bw icon-color-productview"></span>
		</span>
		<span class="v-center"><?php echo $this->__('Only %s left', "<strong>{$this->getStockQty()}</strong>") ?><div class="caret">&nbsp;</div></span>
	</a>
	<table id="<?php echo $this->getDetailsPlaceholderId() ?>" class="availability-only-details no-display">
        <col />
        <col width="1" />
        <thead>
            <tr>
                <th><?php echo $this->__('Product Name') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($this->getChildProducts() as $childProduct) : ?>
            <?php $childProductStockQty = $this->getProductStockQty($childProduct); ?>
            <?php if ($childProductStockQty > 0) : ?>
                <tr>
                    <td><?php echo $childProduct->getName() ?></td>
                    <td class="a-center"><?php echo $childProductStockQty ?></td>
                </tr>
            <?php endif ?>
        <?php endforeach ?>
        </tbody>
    </table>
    <script type="text/javascript">
    //<![CDATA[
    $('<?php echo $this->getPlaceholderId() ?>').observe('click', function(event){
        this.toggleClassName('expanded');
        $('<?php echo $this->getDetailsPlaceholderId() ?>').toggleClassName('no-display');
        event.stop();
        decorateTable('<?php echo $this->getDetailsPlaceholderId() ?>');
    });
    //]]>
    </script>
<?php endif ?>
