<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

 $wsuChannels = array(
					'mywsu-link'=>array('url'=>'https://my.wsu.edu/','text'=>'myWSU'),
					'access-link'=>array('url'=>'http://access.wsu.edu/','text'=>'Access'),
					'policies-link'=>array('url'=>'http://policies.wsu.edu/','text'=>'Policies'),
					'copyright-link'=>array('url'=>'http://copyright.wsu.edu','text'=>'&nbsp;&copy;'),
				);
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>
<header class="spine-header"><a href="http://www.wsu.edu/" id="wsu-signature">Washington State University</a></header>
        <!-- ACTIONS -->
        <section id="wsu-actions" class="spine-actions">
            <!-- Tabs -->
            <ul id="wsu-actions-tabs" class="spine-actions-tabs clearfix">
				<li id="wsu-search-tab" class="spine-search-tab closed" label="Search"><button>Search</button></li>
				<li id="wsu-contact-tab" class="spine-contact-tab closed" label="Contact"><button>Contact</button></li>
				<li id="wsu-share-tab" class="spine-share-tab closed" label="Share"><button>Share</button></li>
				<li id="wsu-print-tab" class="spine-print-tab closed" label="Print"><button>Print</button></li>
            </ul>
        </section><!--/#wsu-actions-->
        <section id="spine-navigation" class="spine-navigation">
            <nav class="spine-sitenav"  data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
			</nav>
        </section><!-- #spine-navigation -->
        <!-- Social and Global Links -->
        <footer class="spine-footer">
            <nav id="wsu-social-channels" class="spine-social-channels">
                <ul>
					
                </ul>
            </nav>
            <nav id="wsu-global-links" class="spine-global-links">
                <ul>
					<?php foreach($wsuChannels as $channel=>$prop) : ?>
                        <li class="<?=$channel?>"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
                    <?php endforeach;  ?>
                </ul>
            </nav>
        </footer>
</nav>

