<?php
	$layout = $this->helper('wsu_themecontrol/layout');
	$layout->set_layoutTarget('catalog_category_view/productlist');
?>
<?php if($this->canShowBlock()): ?>
<?php  $filters = $this->getLayer()->getState()->getFilters(); ?>
<div class="filtering_area <?=$layout->getLayoutBlockClass("filtering_area")?>">
    <h4 class="filtering_button">
        <?php echo $this->__('Filtering') ?> <?php if (!$filters && count($filters)>0): ?> <span class="filters_applied">(<?=count($filters)?> applied)</span><?php endif; ?>
    </h4>
    <div class="filtering_block">
        
        <?php if ($this->getLayer()->getState()->getFilters()): ?>
			<?php echo $this->getStateHtml() ?>
            <div class="actions"><a href="<?php echo $this->getClearUrl() ?>"><?php echo $this->__('Clear All') ?></a></div>
        <?php endif; ?>
        <?php if($this->canShowOptions()): ?>
            <dl id="narrow-by-list">
                <?php $_filters = $this->getFilters() ?>
                <?php foreach ($_filters as $_filter): ?>
                <?php if($_filter->getItemsCount() > 1 && "Category" !== $_filter->getName()): ?>

                    <dt><?php echo $this->__($_filter->getName()) ?></dt>
                    <dd><?php echo $_filter->getHtml() ?></dd>
                <?php endif; ?>
                <?php endforeach; ?>
            </dl>
            <script type="text/javascript">decorateDataList('narrow-by-list')</script>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>
