<div id="localfooter">
	<section class="row sidebar">
        <div class="column one">
            <article>
				<?=$this->getChildHtml() ?> 
                <address><?=$this->getCopyright() ?></address>
                <a href="http://web.wsu.edu/">University Web Communications</a>, Washington State University, PO Box 645910, Pullman, WA, 99164-5910 USA 509-335-2700 <a href="mailto:web.support@wsu.edu">Contact Us</a>
            </article>
        </div>
    </section>
</div>