<?php
/**
 * @var Mage_Page_Block_Html_Header $this
 */
 
 $store = Mage::app()->getStore();
 $name = $store->getFrontendName();
 
 $theme = $this->helper('wsu_themecontrol');	
 $headerInnerBgColor	= $theme->getCfgDesign('header/inner_bg_color');
 $navStretched			= $theme->getCfgDesign('nav/stretched');
 $mainInnerBgColor		= $theme->getCfgDesign('main/inner_bg_color');
 
 $spineColor = $theme->getCfgDesign('spine/spine_color');
 $spineBleed = $theme->getCfgDesign('spine/spine_bleed')?"bleed":"";
 $spineClasses = implode(' ',array($spineColor,$spineBleed));
 $socialChannels = array(
					'facebook'=>array('url'=>'http://facebook.com/wsupullman','text'=>'Facebook'),
					'twitter'=>array('url'=>'http://twitter.com/wsupullman','text'=>'Twitter'),
					'youtube'=>array('url'=>'http://www.youtube.com/washingtonstateuniv','text'=>'YouTube'),
					'social'=>array('url'=>'http://social.wsu.edu','text'=>'Social'),
				);
 $wsuChannels = array(
					'zzusis'=>array('url'=>'https://zzusis.wsu.edu/','text'=>'Zzu<strong>sis</strong>'),
					'access'=>array('url'=>'http://access.wsu.edu/','text'=>'Access'),
					'policies'=>array('url'=>'http://policies.wsu.edu/','text'=>'Policies'),
					'copyright'=>array('url'=>'http://copyright.wsu.edu','text'=>'&nbsp;&copy;'),
				);
 if ( !isset($cropping) ) { $cropping = ''; } else { $cropping = ' '.$cropping; }
 
 $home_link = Mage::helper('core/url')->getHomeUrl();
 $home_text = 'Store Home';
 $homelink = "<li><a href='{$home_link}'>{$home_text}</a></li>";
 $searchOps = array();//array('nix-index','nix-site','nix-wsu','nix-facstaff','nix-students');
 $searchOptionClasses = implode(' ', $searchOps );

?>
<!-- SPINE -->
<div id="spine" class="<?=$spineClasses?>">
    <div id="glue" class="">
        <header><a href="http://www.wsu.edu/" id="wsu-signature">Washington State University</a></header>
        <!-- ACTIONS -->
        <section id="wsu-actions" class="spine-actions">
            <!-- Tabs -->
            <ul id="wsu-actions-tabs" class="spine-actions-tabs clearfix">
				<li id="wsu-search-tab" class="spine-search-tab closed" label="Search"><button>Search</button></li>
				<li id="wsu-contact-tab" class="spine-contact-tab closed" label="Contact"><button>Contact</button></li>
				<li id="wsu-share-tab" class="spine-share-tab closed" label="Share"><button>Share</button></li>
				<li id="wsu-print-tab" class="spine-print-tab closed" label="Print"><button>Print</button></li>
            </ul>
            <section id="wsu-search" class="<?=$searchOptionClasses?> tools closed" data-default="site-search">
                <?php echo $this->getChildHtml('topBar') ?>
                <!--<div id="spine-shortcuts" class="spine-shortcuts"></div>
                </section>-->
            </section>
			
			<div id="contact-details" itemscope itemtype="http://schema.org/Organization"> 
				<span itemprop="department"  content="University Unit"></span> 
				<span itemprop="name" content="Washington State University"></span> 
				<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
					<span itemprop="location" content="<?=nl2br(Mage::getStoreConfig('general/store_information/address'));?>"><?=nl2br(Mage::getStoreConfig('general/store_information/address'));?></span>
				</div>
				<span itemprop="telephone" content="<?=Mage::getStoreConfig('general/store_information/phone');?>"></span>
				<span itemprop="email" content="<?=Mage::getStoreConfig('general/store_information/phone');?>"></span>
				<span itemprop="contactPoint" content="<?=Mage::getStoreConfig('general/store_information/phone');?>"></span>
				<span itemprop="url" content="http://your-unit.wsu.edu"></span>
			</div>
			
			
			
        </section><!--/#wsu-actions-->
        <section id="spine-navigation" class="spine-navigation">
            <nav class="spine-sitenav <?=(!empty($homelink)?'':'homeless')?>">
                <!-- Your navigation list here
                    • Active link should be denoted with an "active" or "current" link on the link's parent li tag.
                    • First link should be home link (otherwise, add "homeless" class to #site nav)
                    • Replace example navigation list below
                -->
                <ul>
                	<?=$homelink?>
                    <?php //echo $this->getChildHtml('topMenu') ?>
                    <?php $_menu = $this->getLayout()->getBlockSingleton('catalog/navigation')->renderCategoriesMenuHtml(0,'')?>
					<?php if($_menu): ?>
                        <?php echo $_menu ?>
                    <?php endif ?>
                </ul>
            </nav>
            <nav class="spine-offsitenav">
                <ul>
                
                <?php 
					$currentUrl = Mage::helper('core/url')->getCurrentUrl();
					$currentUrl = str_ireplace('www.', '', parse_url($currentUrl, PHP_URL_HOST));
					
					$websites = Mage::getModel('core/website')->getCollection();
					$sessionId = Mage::getSingleton("core/session")->getEncryptedSessionId(); 
					if(count($websites)>5):?>
                
                        <li><select id="website-changer" onChange="document.location=this.options[selectedIndex].value">
                                <option selected="selected">Switch stores</option>
                            <?php
                            foreach($websites as $website) {
                                $default_store = $website->getDefaultStore();
                                $url_obj = new Mage_Core_Model_Url();
                                $default_store_path = $url_obj->getBaseUrl(array('_store'=> $default_store->getCode()));
                            ?>
                                <!--<option <?php if(strstr($default_store_path,$currentUrl )>-1):?>selected="selected"<?php endif; ?> value="<?php echo $default_store_path."?SID=".$sessionId ?>"  data-default_store_path="<?=$default_store_path ?>" data-currentUrl="<?=$currentUrl ?>"><?php echo $website->getName()?></option>-->
                                <option value="<?php echo $default_store_path."?SID=".$sessionId ?>"  data-default_store_path="<?=$default_store_path ?>" data-currentUrl="<?=$currentUrl ?>">
                                    <?php echo $website->getName()?>
                                </option>
                            <?php
                            }
                            ?>
                            </select>
                        </li>
                    <?php else: ?>
<?php
                        foreach($websites as $website) {
                            $default_store = $website->getDefaultStore();
							if(!empty($default_store)){
								$url_obj = new Mage_Core_Model_Url();
								$default_store_path = $url_obj->getBaseUrl(array('_store'=> $default_store->getCode()));
							?>
						<li><a href="<?php echo $default_store_path."?SID=".$sessionId ?>"><?php echo $website->getName()?></a></li>
							<?php
							}
                        }
                        ?>
                    <?php endif; ?>
                    <!--<li><a href="">Offsite Link</a></li>
                    <li><a href="">Another</a></li>-->
                </ul>
            </nav>
        </section><!-- #spine-navigation -->
        <!-- Social and Global Links -->
        <footer class="spine-footer">
            <nav id="wsu-social-channels" class="spine-social-channels">
                <ul>
				<?php
                    foreach($socialChannels as $channel=>$prop) {
					?>
						<li class="<?=$channel?>-channel"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
					<?php
                    }
                ?>
                </ul>
            </nav>
            <nav id="wsu-global-links" class="spine-global-links">
                <ul>
				<?php
                    foreach($wsuChannels as $channel=>$prop) {
                    ?>
                        <li id="<?=$channel?>"><a href="<?=(isset($prop['url'])?$prop['url']:'#')?>"><?=(isset($prop['text'])?$prop['text']:'#')?></a></li>
                    <?php
                    }
                ?>
                </ul>
            </nav>        
            <!-- <small class="copyright-link"><a href="http://copyright.wsu.edu">&copy; Washington State University</a></small> -->
        </footer>
    </div><!--/glue-->
</div><!--/spine-->
<!-- /SPINE -->