<?php $theme = Mage::helper('wsu_themecontrol'); ?>
<meta http-equiv="Content-Type" content="<?php echo $this->getContentType() ?>" />
<title><?php echo $this->getTitle() ?></title>
<meta name="description" content="<?php echo htmlspecialchars($this->getDescription()) ?>" />
<meta name="keywords" content="<?php echo htmlspecialchars($this->getKeywords()) ?>" />
<meta name="robots" content="<?php echo htmlspecialchars($this->getRobots()) ?>" />
<!--<link rel="shortcut icon" href="https://repo.wsu.edu/spine/1/favicon.ico" />-->
<link rel="shortcut icon" href="<?php echo $this->getFaviconFile(); ?>" type="image/x-icon" />

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
<?php echo $this->helper('core/js')->getTranslatorScript() ?>
<?php echo $this->getIncludes() ?>

<noscript><style>#spine .spine-sitenav ul ul li { display: block !important; }</style></noscript>

<!-- DOCS -->
<link type="text/plain" rel="author" href="http://repo.wsu.edu/spine/1/authors.txt" />
<link type="text/html" rel="docs" href="http://brand.wsu.edu" />

<?php if ($theme->getCfgDesign('font/primary_font_family_group') == 'google'): ?>
	<?php //Include Google Fonts
		$amp = '&amp;';
		$charSubset = '';
		if ($subsets = $theme->getCfgDesign('font/primary_char_subset')) {
			$charSubset = "{$amp}subset={$subsets}";
		}
	
		$fontWeight = '';
		if ($weight = $theme->getCfgDesign('font/primary_font_weight')) {
			$fontWeight = ':' . $weight;
		}
	?>
	<link href='//fonts.googleapis.com/css?family=<?php echo str_replace(' ', '+', $theme->getCfgDesign('font/primary_font_family')); 
		echo $fontWeight; echo $charSubset; ?>' rel='stylesheet' type='text/css' />
<?php endif;?>

