<?php
/**
 * @see Mage_CatalogInventory_Block_Stockqty_Default
 */
?>
<?php if($this->isMsgVisible()): ?>
	<span class="availability-only feature v-centered-content">
		<span class="v-center">
			<span class="icon i-lowstock icon-color-productview"></span>
		</span>
		<span class="v-center"
        	title="<?php echo $this->__('Only %s left', ($this->getStockQty())) ?>"><?php echo $this->__('Only %s left', "<strong>{$this->getStockQty()}</strong>") ?></span>
	</span>
<?php endif ?>
